language: rust
dist: trusty

rust:
  - stable

before_install:
  - |
    source $HOME/.nvm/nvm.sh  
    nvm install stable
    nvm use stable
    node -v
    npm -v

install:
  - rustup component add clippy
  - rustup component add rustfmt

jobs:
  include:
    - stage: Tests
      name: Lint
      script:
        - npm run format -- --all -- --check
        - npm run lint
    - script: npm run test
      name: Test
