language: rust
dist: trusty

rust:
  - stable

before_install:
  - |
    source $HOME/.nvm/nvm.sh  
    nvm install stable
    nvm use stable
    node -v
    npm -v

install:
  - rustup component add clippy

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Compile
      script: npm run check
    - stage: Test
      script: npm run test
