language: rust
dist: trusty

rust:
  - stable

before_install:
  - |
    source $HOME/.nvm/nvm.sh  
    nvm install stable
    nvm use stable
    node -v
    npm -v

install:
  - rustup component add clippy

jobs:
  include:
    - stage: Tests
      name: Lint
      script: npm run lint
    - script: npm run check
      name: Compile
    - script: npm run test
      name: Test
